version: "2"
services:
  web:
    build: .
    ports:
      - "27999:27999"
      - "27925:27925"
      - "27950:27950"
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"
  geth:
    command: bin/geth1
    build: 
      context: z_docker/docker-geth
      dockerfile: Dockerfile
