// FILE IS GENERATED! DON'T EDIT! Generated by apigen.js Fri Nov 03 2017 23:55:27 GMT+0200 (EET)

const
    logger = require('../logger'),
    http = require('http');

async function ping(host) {
    await http.get(host + '/api/v1/ping', (resp)=>{
        logger.info('ping success');
    }).on('error', (err)=>{
        logger.error('ping error', err);
    });
};

async function nodeRate(host) {
    await http.get(host + '/api/v1/nodeRate', (resp)=>{
        logger.info('nodeRate success');
    }).on('error', (err)=>{
        logger.error('nodeRate error', err);
    });
};

async function nodeState(host) {
    await http.get(host + '/api/v1/nodeState', (resp)=>{
        logger.info('nodeState success');
    }).on('error', (err)=>{
        logger.error('nodeState error', err);
    });
};

async function poolNotifications(host) {
    await http.get(host + '/api/v1/poolNotifications', (resp)=>{
        logger.info('poolNotifications success');
    }).on('error', (err)=>{
        logger.error('poolNotifications error', err);
    });
};

module.exports = {
    ping: ping,
    nodeRate: nodeRate,
    nodeState: nodeState,
    poolNotifications: poolNotifications
};
