// FILE IS GENERATED! DON'T EDIT! Generated by apigen.js Tue Nov 07 2017 09:59:20 GMT+0200 (EET)

const
    logger = require('../logger'),
	got = require('got');

async function ping(host) {
    var res = (await got(host + '/api/v1/ping', {json:true})).body;
    return res;
};

async function connect(host, apiVersion, apiKey) {
    var res = (await got(host + '/api/v1/connect' + '/' + apiVersion + '/' + apiKey, {json:true})).body;
    return res;
};

async function disconnect(host, connectionId) {
    var res = (await got(host + '/api/v1/disconnect' + '/' + connectionId, {json:true})).body;
    return res;
};

async function nodeRate(host, connectionId, token) {
    var res = (await got(host + '/api/v1/nodeRate' + '/' + connectionId + '/' + token, {json:true})).body;
    return res;
};

async function nodeState(host, connectionId, nodeId) {
    var res = (await got(host + '/api/v1/nodeState' + '/' + connectionId + '/' + nodeId, {json:true})).body;
    return res;
};

async function poolNotifications(host, connectionId) {
    var res = (await got(host + '/api/v1/poolNotifications' + '/' + connectionId, {json:true})).body;
    return res;
};

module.exports = {
    ping: ping,
    connect: connect,
    disconnect: disconnect,
    nodeRate: nodeRate,
    nodeState: nodeState,
    poolNotifications: poolNotifications
}
