// FILE IS GENERATED! DON'T EDIT! Generated by apigen.js
function initRoute(app, api, options) {

    app.get('/api/v1/ping/:connectionId', api.getPing);

//    app.post('/api/v1/login/:username/:password', options.passport.authenticate('local'), api.postLogin);
//    app.post('/api/v1/login', options.passport.authenticate('local'), api.postLogin);
/*    var fn = options.passport.authenticate('local')
    app.post('/api/v1/login', function fn1(req, res, next) {
        fn(req, res, next);
    }, api.postLogin);*/

    app.get('/api/v1/connect/:apiVersion/:apiKey', api.getConnect);

    app.get('/api/v1/disconnect/:connectionId', api.getDisconnect);

    app.get('/api/v1/nodeTickers/:connectionId/:token', api.getNodeTickers);

    app.get('/api/v1/nodeState/:connectionId/:nodeId', api.getNodeState);

    app.get('/api/v1/poolNotifications/:connectionId/:index/:count', api.getPoolNotifications);

    app.get('/api/v1/nodeOnOff/:connectionId/:onoff', api.getNodeOnOff);

}

module.exports = {
    'initRoute': initRoute
}
