// FILE IS GENERATED! DON'T EDIT! Generated by apigen.js
function initRoute(app, api) {

    app.use('/api/v1/ping/:connectionId', api.getPing);

    app.use('/api/v1/connect/:apiVersion/:apiKey', api.getConnect);

    app.use('/api/v1/disconnect/:connectionId', api.getDisconnect);

    app.use('/api/v1/nodeTickers/:connectionId/:token', api.getNodeTickers);

    app.use('/api/v1/nodeState/:connectionId/:nodeId', api.getNodeState);

    app.use('/api/v1/poolNotifications/:connectionId/:index/:count', api.getPoolNotifications);

    app.use('/api/v1/nodeOnOff/:connectionId/:onoff', api.getNodeOnOff);

}

module.exports = {
    'initRoute': initRoute
}
