// FILE IS GENERATED! DON'T EDIT! Generated by apigen.js Fri Nov 03 2017 23:55:27 GMT+0200 (EET)

const
    api = require('./server-api');

function initRoute(app) {

    app.use('/api/v1/ping', api.getPing);

    app.use('/api/v1/nodeRate', api.getNodeRate);

    app.use('/api/v1/nodeState', api.getNodeState);

    app.use('/api/v1/poolNotifications', api.getPoolNotifications);

}

module.exports = {
    'initRoute': initRoute
};
